on:
  push:
    branches:
    - main
    
jobs:
  build:
    name: build vue app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install and build
      run: |
        npm install
        npm run build-only
        
